// @ts-nocheck
import type { RetrievalTraceReplayScenario } from "./retrieval-trace-replay-benchmark"

// Stable replay fixtures promoted from fresh ambiguous trace capture runs.
// These give the replay lane durable coverage even when the live trace file changes.
export const REAL_RETRIEVAL_TRACE_REPLAY_SCENARIOS: RetrievalTraceReplayScenario[] = [
  {
    id: "real_trace_replay_file_vs_compaction_owner",
    query: "which file owns the short filename retention logic for compaction",
    detail: "ambiguous between exact file lookup and compaction retention memory",
    expectedIntent: "file",
    expectedSecondaryIntent: "compaction",
    expectedConfidence: "low",
    expectedStrategy: "dual_intent_blend",
    expectedTopDocumentID: "capture-seed-real_compaction_short_symbol_retention",
    candidates: [
      {
        rank: 1,
        documentID: "capture-seed-real_compaction_short_symbol_retention",
        chunkID: "capture-seed-real_compaction_short_symbol_retention-chunk-0",
        sourceType: "note",
        title: "real_compaction_short_symbol_retention compaction",
        score: 6,
        rerankScore: 6.354245954216038,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:compaction] short technical symbol retention during compaction Operator query: preserve terse symbols filenames and identifiers through prompt compaction.",
      },
      {
        rank: 2,
        documentID: "capture-seed-real_compaction_short_filename_anchor",
        chunkID: "capture-seed-real_compaction_short_filename_anchor-chunk-0",
        sourceType: "note",
        title: "real_compaction_short_filename_anchor compaction",
        score: 6,
        rerankScore: 6.329983164553722,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:compaction] short filename retention through compaction baton Operator query: keep service.ts and foo.ts alive through compaction.",
      },
      {
        rank: 3,
        documentID: "capture-seed-real_file_prompt_registry_owner",
        chunkID: "capture-seed-real_file_prompt_registry_owner-chunk-0",
        sourceType: "note",
        title: "real_file_prompt_registry_owner file",
        score: 5,
        rerankScore: 5.386500602909469,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:file] file lookup for retrieval prompt preset registry Operator query: which file defines the shared qwen3 retrieval prompt registry for memory decision failure file and compaction.",
      },
    ],
  },
  {
    id: "real_trace_replay_recovery_vs_decision_fallback_rule",
    query: "what fixed provider fallback divergence and what rule did we keep afterward",
    detail: "ambiguous between recovery path and preserved decision rule",
    expectedIntent: "decision",
    expectedSecondaryIntent: "recovery",
    expectedConfidence: "low",
    expectedStrategy: "dual_intent_blend",
    expectedTopDocumentID: "capture-seed-real_recovery_fallback_parity",
    candidates: [
      {
        rank: 1,
        documentID: "capture-seed-real_recovery_fallback_parity",
        chunkID: "capture-seed-real_recovery_fallback_parity-chunk-0",
        sourceType: "note",
        title: "real_recovery_fallback_parity recovery",
        score: 5,
        rerankScore: 5.296078262731896,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:recovery] provider fallback ranking parity recovery Operator query: find the regression where provider rerank and fallback rerank diverged and how we fixed it.",
      },
      {
        rank: 2,
        documentID: "capture-seed-real_recovery_adversarial_file_vs_failure",
        chunkID: "capture-seed-real_recovery_adversarial_file_vs_failure-chunk-0",
        sourceType: "note",
        title: "real_recovery_adversarial_file_vs_failure recovery",
        score: 5,
        rerankScore: 5.207019667802706,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:recovery] adversarial mix of owner-file lookup with a recovery question Operator query: which file had that fallback bug where ordering changed under us and what fixed it.",
      },
      {
        rank: 3,
        documentID: "capture-seed-real_decision_qwen_instruction_contract",
        chunkID: "capture-seed-real_decision_qwen_instruction_contract-chunk-0",
        sourceType: "note",
        title: "real_decision_qwen_instruction_contract decision",
        score: 5,
        rerankScore: 5.173972250159805,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:decision] instruction-resolution contract for qwen3 embedder and reranker Operator query: what settled the rule that qwen3 must receive real retrieval instructions instead of bare preset ids.",
      },
    ],
  },
  {
    id: "real_trace_replay_file_vs_decision_runtime_models",
    query: "which file shows observed runtime retrieval models and what rule required that",
    detail: "ambiguous between exact surface owner and settled observability rule",
    expectedIntent: "file",
    expectedSecondaryIntent: "decision",
    expectedConfidence: "low",
    expectedStrategy: "dual_intent_blend",
    expectedTopDocumentID: "capture-seed-real_decision_runtime_vs_requested_models",
    candidates: [
      {
        rank: 1,
        documentID: "capture-seed-real_decision_runtime_vs_requested_models",
        chunkID: "capture-seed-real_decision_runtime_vs_requested_models-chunk-0",
        sourceType: "note",
        title: "real_decision_runtime_vs_requested_models decision",
        score: 6,
        rerankScore: 6.4804938261204725,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:decision] truthful runtime model reporting as a settled substrate rule Operator query: what was the rule about showing observed runtime retrieval models instead of only requested policy defaults.",
      },
      {
        rank: 2,
        documentID: "capture-seed-real_decision_adversarial_rule_vs_file",
        chunkID: "capture-seed-real_decision_adversarial_rule_vs_file-chunk-0",
        sourceType: "note",
        title: "real_decision_adversarial_rule_vs_file decision",
        score: 6,
        rerankScore: 6.466666666666667,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:decision] adversarial mix of owner-file phrasing with a governing retrieval rule request Operator query: which file had the rule about auto and quality not sharing vectors and what was the rule exactly.",
      },
      {
        rank: 3,
        documentID: "capture-seed-real_recovery_adversarial_file_vs_failure",
        chunkID: "capture-seed-real_recovery_adversarial_file_vs_failure-chunk-0",
        sourceType: "note",
        title: "real_recovery_adversarial_file_vs_failure recovery",
        score: 6,
        rerankScore: 6.335410196624968,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:recovery] adversarial mix of owner-file lookup with a recovery question Operator query: which file had that fallback bug where ordering changed under us and what fixed it.",
      },
    ],
  },
  {
    id: "real_trace_replay_file_vs_decision_cache_identity",
    query: "which file actually owns the settled retrieval rule about embedding cache identity",
    detail: "ambiguous between exact owner file lookup and settled decision recall",
    expectedIntent: "file",
    expectedSecondaryIntent: "decision",
    expectedConfidence: "low",
    expectedStrategy: "dual_intent_blend",
    expectedTopDocumentID: "capture-seed-real_decision_adversarial_rule_vs_file",
    candidates: [
      {
        rank: 1,
        documentID: "capture-seed-real_decision_adversarial_rule_vs_file",
        chunkID: "capture-seed-real_decision_adversarial_rule_vs_file-chunk-0",
        sourceType: "note",
        title: "real_decision_adversarial_rule_vs_file decision",
        score: 6,
        rerankScore: 6.4,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:decision] adversarial mix of owner-file phrasing with a governing retrieval rule request Operator query: which file had the rule about auto and quality not sharing vectors and what was the rule exactly.",
      },
      {
        rank: 2,
        documentID: "capture-seed-real_file_adversarial_owner_vs_rule",
        chunkID: "capture-seed-real_file_adversarial_owner_vs_rule-chunk-0",
        sourceType: "note",
        title: "real_file_adversarial_owner_vs_rule file",
        score: 6,
        rerankScore: 6.350324524872685,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:file] owner-file lookup wrapped around a governing instruction rule Operator query: which file owns the qwen instruction contract rule for embed and rerank requests.",
      },
      {
        rank: 3,
        documentID: "capture-seed-real_decision_embedding_identity_signature",
        chunkID: "capture-seed-real_decision_embedding_identity_signature-chunk-0",
        sourceType: "note",
        title: "real_decision_embedding_identity_signature decision",
        score: 5,
        rerankScore: 5.392837100659193,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:decision] semantic embedding identity and cache versioning rule Operator query: what exactly defines embedding cache identity for a retrieval chunk now.",
      },
    ],
  },
  {
    id: "real_trace_replay_task_pattern_vs_recovery_truthful_first",
    query: "what was the pattern where we made retrieval truthful first before fixing the rest",
    detail: "ambiguous between recovery episode and reusable task pattern",
    expectedIntent: "task_pattern",
    expectedSecondaryIntent: "recovery",
    expectedConfidence: "low",
    expectedStrategy: "dual_intent_blend",
    expectedTopDocumentID: "capture-seed-real_task_pattern_observability_hardening",
    candidates: [
      {
        rank: 1,
        documentID: "capture-seed-real_task_pattern_observability_hardening",
        chunkID: "capture-seed-real_task_pattern_observability_hardening-chunk-0",
        sourceType: "note",
        title: "real_task_pattern_observability_hardening task_pattern",
        score: 10,
        rerankScore: 10.562926251752643,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:task_pattern] observability hardening before eval expansion pattern Operator query: show the pattern where we made the substrate truthful first and then expanded the benchmark.",
      },
      {
        rank: 2,
        documentID: "capture-seed-real_task_pattern_expand_until_breaks",
        chunkID: "capture-seed-real_task_pattern_expand_until_breaks-chunk-0",
        sourceType: "note",
        title: "real_task_pattern_expand_until_breaks task_pattern",
        score: 8,
        rerankScore: 8.548821299948452,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:task_pattern] keep expanding the real-case benchmark before overfitting prompts Operator query: what was the pattern for growing the real retrieval eval set until the first crack shows up instead of tuning blind.",
      },
      {
        rank: 3,
        documentID: "capture-seed-real_task_pattern_benchmark_then_production",
        chunkID: "capture-seed-real_task_pattern_benchmark_then_production-chunk-0",
        sourceType: "note",
        title: "real_task_pattern_benchmark_then_production task_pattern",
        score: 8,
        rerankScore: 8.465130254709532,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:task_pattern] benchmark first then production rollout pattern Operator query: what was the pattern for proving a retrieval win in the benchmark before wiring it into production.",
      },
    ],
  },
  {
    id: "real_trace_replay_task_pattern_vs_decision_benchmark_first",
    query: "what was our benchmark-first then production pattern and what decision did it preserve",
    detail: "ambiguous between execution pattern and governing decision",
    expectedIntent: "task_pattern",
    expectedSecondaryIntent: "decision",
    expectedConfidence: "low",
    expectedStrategy: "dual_intent_blend",
    expectedTopDocumentID: "capture-seed-real_task_pattern_adversarial_fix_rule_verify",
    candidates: [
      {
        rank: 1,
        documentID: "capture-seed-real_task_pattern_adversarial_fix_rule_verify",
        chunkID: "capture-seed-real_task_pattern_adversarial_fix_rule_verify-chunk-0",
        sourceType: "note",
        title: "real_task_pattern_adversarial_fix_rule_verify task_pattern",
        score: 8,
        rerankScore: 8.319460920839001,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:task_pattern] crossed decision-language and task-pattern-language where the target is the execution pattern Operator query: what was our benchmark-first then production pattern and what decision did it preserve.",
      },
      {
        rank: 2,
        documentID: "capture-seed-real_task_pattern_benchmark_then_production",
        chunkID: "capture-seed-real_task_pattern_benchmark_then_production-chunk-0",
        sourceType: "note",
        title: "real_task_pattern_benchmark_then_production task_pattern",
        score: 7,
        rerankScore: 7.360994102557712,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:task_pattern] benchmark first then production rollout pattern Operator query: what was the pattern for proving a retrieval win in the benchmark before wiring it into production.",
      },
      {
        rank: 3,
        documentID: "capture-seed-real_task_pattern_classifier_alignment",
        chunkID: "capture-seed-real_task_pattern_classifier_alignment-chunk-0",
        sourceType: "note",
        title: "real_task_pattern_classifier_alignment task_pattern",
        score: 7,
        rerankScore: 7.338822606998534,
        outcomeScore: 1,
        feedbackScore: 0,
        snippet:
          "opencode retrieval substrate march 2026 [intent:task_pattern] shared classifier alignment pattern across production and harness Operator query: what was the pattern for fixing classifier drift by sharing one production router with the benchmark.",
      },
    ],
  },
]
